### ISSUE TITLE
Set up labels, milestones, projects consistently across repos

### ISSUE THREAD

**Issue by cornelius** [dtr-org/unit-e-project#101]
The [unit-e](https://github.com/dtr-org/unit-e) repo has a clean setup of milestones, projects, and labels according to our [issue](https://github.com/dtr-org/unit-e-docs/blob/master/project/issues.md) and [milestone](https://github.com/dtr-org/unit-e-docs/blob/master/project/milestones.md) conventions now.

The other repos should be set up in a way consistent with that, reusing the same definitions and settings as far as they apply:

* [x] [desktop wallet](https://github.com/dtr-org/unit-e-desktop)
* [x] [docs](https://github.com/dtr-org/docs.unit-e.io)
* [x] [UIPs](https://github.com/dtr-org/uips)
* [x] [clonemachine](https://github.com/dtr-org/clonemachine)
* [x] [unit-e-docs](https://github.com/dtr-org/unit-e-docs)

Some automation is desirable but a fully automatic setup of all data across repositories might be overkill, especially for data which isn't changed too often (see also #93).
